In [1]:
import duckdb

In [2]:
conn=duckdb.connect(r"D:\SEC.gov project\Analysis Project\credit_risk.db")

In [3]:
conn.sql("""
         SELECT COUNT(*)
         FROM tag
         """).df()

   count_star()
0        199968

In [4]:
conn.sql("""
         SUMMARIZE tag
         """).df()

,column_name,column_type,min,max,approx_unique,avg,std,q25,q50,q75,count,null_percentage
0,tag,VARCHAR,AAMCommonStockIssuedperMPGCommonStockasPartoft...,warrantsWereExcluded,34157,<NA>,<NA>,<NA>,<NA>,<NA>,199968,0.00
1,version,VARCHAR,0000014195-19-000008,us-gaap/2025,2724,<NA>,<NA>,<NA>,<NA>,<NA>,199968,0.00
2,custom,VARCHAR,0,1,2,<NA>,<NA>,<NA>,<NA>,<NA>,199968,0.00
3,abstract,VARCHAR,0,0,1,<NA>,<NA>,<NA>,<NA>,<NA>,199968,0.00
4,datatype,VARCHAR,area,volume,12,<NA>,<NA>,<NA>,<NA>,<NA>,199968,0.00
5,iord,VARCHAR,D,I,2,<NA>,<NA>,<NA>,<NA>,<NA>,199968,0.00
6,crdr,VARCHAR,C,D,2,<NA>,<NA>,<NA>,<NA>,<NA>,199968,21.69
7,tlabel,VARCHAR,% of Total Revenue,working capital and other impact - France Tran...,24717,<NA>,<NA>,<NA>,<NA>,<NA>,199968,0.00
8,doc,VARCHAR,Amount of liability after subsequent adjustme...,xercise price per share or per unit of warrant...,28917,<NA>,<NA>,<NA>,<NA>,<NA>,199968,3.03

In [3]:
conn.execute("""
             CREATE TABLE clean.tag AS 
             SELECT 
             TRIM(tag) AS tag,
             TRIM(version) AS version,
             CAST(custom AS BOOLEAN) AS custom,
             CAST(abstract AS BOOLEAN) AS abstract,
             TRIM(datatype) as datatype,
             TRIM(iord) as iord,
             TRIM(crdr) as crdr,
             TRIM(tlabel) as tlabel,
             TRIM(doc) as doc
             FROM tag
             """)