In [2]:
import pandas as pd

In [4]:
sub=pd.read_csv(r'D:\SEC.gov project\Enquiry Dataset\sub.tsv', sep='\t')

In [5]:
sub.to_csv(r'D:\SEC.gov project\Enquiry Dataset\sub.csv', index=False)

In [6]:
tag=pd.read_csv(r'D:\SEC.gov project\Enquiry Dataset\tag.tsv', sep='\t')

In [7]:
tag.to_csv(r'D:\SEC.gov project\Enquiry Dataset\tag.csv', index=False)

In [61]:
tag[tag['tag'].str.lower().str.contains('invest')]

,tag,version,custom,abstract,datatype,iord,crdr,tlabel,doc
831,AAAInvestmentVehiclesMember,0001004315-26-000006,1,1,member,NaN,NaN,AAA Investment Vehicles [Member],AAA Investment Vehicles [Member]
833,AaaToBbbInvestmentGradeMember,0001104659-26-075175,1,1,member,NaN,NaN,AAA to BBB (Investment Grade) [Member],This member stands for AAA to BBB (Investment ...
837,AAM241ThirdNPAWithInstitutionalInvestorsMember,0000353184-26-000054,1,1,member,NaN,NaN,AAM 24-1 Third NPA with Institutional Investor...,AAM 24-1 Third NPA with Institutional Investors
927,AccessToInvestmentsMember,0001213900-26-065162,1,1,member,NaN,NaN,Access to Investments [Member],NaN
928,AccessToInvestmentsMember,0001213900-26-067670,1,1,member,NaN,NaN,Access to Investments [Member],NaN

In [12]:
dim=pd.read_csv(r"D:\SEC.gov project\Enquiry Dataset\dim.tsv", sep='\t')

In [13]:
dim.to_csv(r"D:\SEC.gov project\Enquiry Dataset\dim.csv", index=False)

In [9]:
num=pd.read_csv(r"D:\SEC.gov project\Enquiry Dataset\num.tsv", sep='\t')

In [10]:
num.to_csv(r"D:\SEC.gov project\Enquiry Dataset\num.csv", index=False)

In [7]:
pd.set_option('display.max_columns', 500)

In [64]:
num[(num['tag'].str.lower().str.contains('payments'))]

,adsh,tag,version,ddate,qtrs,uom,dimh,iprx,value,footnote,footlen,dimn,coreg,durp,datp,dcml
59,0000001961-26-000014,FinanceLeaseLiabilityPaymentsDueInNextRollingT...,us-gaap/2025,20250331,0,USD,0x00000000,0,773279.0,NaN,0,0,NaN,0.000000,0.0,0
60,0000001961-26-000014,FinanceLeaseLiabilityPaymentsDueInRollingYearFive,us-gaap/2025,20250331,0,USD,0x00000000,0,0.0,NaN,0,0,NaN,0.000000,0.0,0
61,0000001961-26-000014,FinanceLeaseLiabilityPaymentsDueInRollingYearFour,us-gaap/2025,20250331,0,USD,0x00000000,0,0.0,NaN,0,0,NaN,0.000000,0.0,0
62,0000001961-26-000014,FinanceLeaseLiabilityPaymentsDueInRollingYearT...,us-gaap/2025,20250331,0,USD,0x00000000,0,0.0,NaN,0,0,NaN,0.000000,0.0,0
63,0000001961-26-000014,FinanceLeaseLiabilityPaymentsDueInRollingYearTwo,us-gaap/2025,20250331,0,USD,0x00000000,0,0.0,NaN,0,0,NaN,0.000000,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
873375,0002104052-26-000081,ProceedsFromRepaymentsOfShortTermDebt,us-gaap/2025,20260331,1,USD,0xba19ccf31b69a66a77fdc92e726e5433,0,109000.0,NaN,0,1,NewEnviri,0.024658,0.0,-3
873490,0002104052-26-000081,RepaymentsOfSecuredDebt,us-gaap/2025,20250331,1,USD,0x00000000,0,1250000.0,NaN,0,0,NaN,0.024658,0.0,-3
873491,0002104052-26-000081,RepaymentsOfSecuredDebt,us-gaap/2025,20250331,1,USD,0xba19ccf31b69a66a77fdc92e726e5433,0,1250000.0,NaN,0,1,NewEnviri,0.024658,0.0,-3
873492,0002104052-26-000081,RepaymentsOfSecuredDebt,us-gaap/2025,20260331,1,USD,0x00000000,0,1250000.0,NaN,0,0,NaN,0.024658,0.0,-3
873493,0002104052-26-000081,RepaymentsOfSecuredDebt,us-gaap/2025,20260331,1,USD,0xba19ccf31b69a66a77fdc92e726e5433,0,1250000.0,NaN,0,1,NewEnviri,0.024658,0.0,-3

In [29]:
txt=pd.read_csv(r"D:\SEC.gov project\txt.tsv", sep='\t',nrows=1000)

In [30]:
txt.head(10)

,adsh,tag,version,ddate,qtrs,iprx,lang,dcml,durp,datp,dimh,dimn,coreg,escaped,srclen,txtlen,footnote,footlen,context,value
0,0000001961-26-000006,AmendmentFlag,dei/2026,20260331,0,0,en-US,32767,0.0,5.0,0x00000000,0,NaN,0,5,5,NaN,0,AsOf2026-03-26,false
1,0000001961-26-000006,CityAreaCode,dei/2026,20260331,0,0,en-US,32767,0.0,5.0,0x00000000,0,NaN,0,5,5,NaN,0,AsOf2026-03-26,(917)
2,0000001961-26-000006,CurrentFiscalYearEndDate,dei/2026,20260331,0,0,en-US,32767,0.0,5.0,0x00000000,0,NaN,0,7,7,NaN,0,AsOf2026-03-26,--12-31
3,0000001961-26-000006,DocumentPeriodEndDate,dei/2026,20260331,0,0,en-US,32767,0.0,5.0,0x00000000,0,NaN,0,10,10,NaN,0,AsOf2026-03-26,2026-03-26
4,0000001961-26-000006,DocumentType,dei/2026,20260331,0,0,en-US,32767,0.0,5.0,0x00000000,0,NaN,0,3,3,NaN,0,AsOf2026-03-26,8-K
5,0000001961-26-000006,EntityAddressAddressLine1,dei/2026,20260331,0,0,en-US,32767,0.0,5.0,0x00000000,0,NaN,0,19,19,NaN,0,AsOf2026-03-26,4775 Collins Avenue
6,0000001961-26-000006,EntityAddressAddressLine1,dei/2026,20260331,0,0,en-US,32767,0.0,5.0,0x64e610ddd230f00dbd801c950921ad52,1,NaN,0,13,13,NaN,0,From2026-03-262026-03-26_dei_FormerAddressMember,11 Royal Road
7,0000001961-26-000006,EntityAddressCityOrTown,dei/2026,20260331,0,0,en-US,32767,0.0,5.0,0x00000000,0,NaN,0,11,11,NaN,0,AsOf2026-03-26,Miami Beach
8,0000001961-26-000006,EntityAddressCityOrTown,dei/2026,20260331,0,0,en-US,32767,0.0,5.0,0x64e610ddd230f00dbd801c950921ad52,1,NaN,0,9,9,NaN,0,From2026-03-262026-03-26_dei_FormerAddressMember,Brookline
9,0000001961-26-000006,EntityAddressPostalZipCode,dei/2026,20260331,0,0,en-US,32767,0.0,5.0,0x00000000,0,NaN,0,5,5,NaN,0,AsOf2026-03-26,33140

In [22]:
ren=pd.read_csv(r"D:\SEC.gov project\ren.tsv", sep='\t',nrows=1000)

In [23]:
ren.head(10)

,adsh,report,rfile,menucat,shortname,longname,roleuri,parentroleuri,parentreport,ultparentrpt
0,0000001961-26-000006,1,H,C,Cover,00000001 - Document - Cover,http://WDDD/role/Cover,NaN,NaN,NaN
1,0000008063-26-000032,1,H,C,Cover,0000001 - Document - Cover,http://www.astronics.com/role/Cover,NaN,NaN,NaN
2,0000015847-26-000009,1,H,C,Cover,0000001 - Document - Cover,http://www.buks.com/role/Cover,NaN,NaN,NaN
3,0000028917-26-000015,1,H,C,Document and Entity Information,00090 - Document - Document and Entity Informa...,http://dillards.com/role/DocumentDocumentAndEn...,NaN,NaN,NaN
4,0000049071-26-000027,1,H,C,Cover,0000001 - Document - Cover,http://www.humana.com/role/Cover,NaN,NaN,NaN
5,0000067215-26-000028,1,H,C,Document and Entity Information Document,0000001 - Document - Document and Entity Infor...,http://www.dycomind.com/role/DocumentandEntity...,NaN,NaN,NaN
6,0000059558-26-000038,1,H,C,Cover,0000001 - Document - Cover,http://lincolnfinancial.com/role/Cover,NaN,NaN,NaN
7,0000105770-26-000080,1,H,C,Cover Page,0000001 - Document - Cover Page,http://www.westpharma.com/role/CoverPage,NaN,NaN,NaN
8,0000060519-26-000024,1,H,C,Cover,0000001 - Document - Cover,http://www.lpcorp.com/role/Cover,NaN,NaN,NaN
9,0000717538-26-000070,1,H,C,Cover Page,0000001 - Document - Cover Page,http://arrowfinancial.com/role/CoverPage,NaN,NaN,NaN

In [24]:
txt=pd.read_csv(r"D:\SEC.gov project\txt.tsv", sep='\t',nrows=1000)

In [27]:
txt[['tag','value']].head(20)

                                             tag                value
0                                  AmendmentFlag                false
1                                   CityAreaCode                (917)
2                       CurrentFiscalYearEndDate              --12-31
3                          DocumentPeriodEndDate           2026-03-26
4                                   DocumentType                  8-K
5                      EntityAddressAddressLine1  4775 Collins Avenue
6                      EntityAddressAddressLine1        11 Royal Road
7                        EntityAddressCityOrTown          Miami Beach
8                        EntityAddressCityOrTown            Brookline
9                     EntityAddressPostalZipCode                33140
10                    EntityAddressPostalZipCode                02445
11                  EntityAddressStateOrProvince                   FL
12                  EntityAddressStateOrProvince                   MA
13                         EntityCentralIndexKey           0000001961
14                   EntityEmergingGrowthCompany                false
15                              EntityFileNumber           000-284115
16           EntityIncorporationStateCountryCode                   DE
17  EntityInformationFormerLegalOrRegisteredName          Worlds Inc.
18                          EntityRegistrantName         GEMAXEL INC.
19                 EntityTaxIdentificationNumber           22-1848316

In [15]:
cal=pd.read_csv(r"D:\SEC.gov project\Enquiry Dataset\cal.tsv", sep='\t')

In [16]:
cal.to_csv(r"D:\SEC.gov project\Enquiry Dataset\cal.csv", index=False)

In [1]:
import pandas as pd 
import duckdb

In [2]:
conn=duckdb.connect(r"D:\SEC.gov project\database\credit_risk.db")

In [9]:
conn.sql("""
         SELECT 
         s.cik,
         s.name,
         m.*
         FROM gold.fact_financial_metrics m
         JOIN clean.sub S 
         ON m.accession_number=s.adsh
         AND m.period_end = s.period
         WHERE s.cik= '1062231' 
         AND s.form = '10-K'
         ORDER BY m.period_end ASC
         """).df()

,cik,name,accession_number,period_end,current_ratio,quick_ratio,cash_ratio,net_working_capital,interest_coverage_ratio,ocf_debt_ratio,debt_to_assets_ratio,short_term_debt_ratio,cash_earnings_conversion,fcf_to_debt_ratio,return_on_assets,filed
0,1062231,AMERICAN AXLE & MANUFACTURING HOLDINGS INC,0001062231-19-000013,2018-12-31,1.50,NaN,0.35,673000000.0,0.49,NaN,0.02,0.03,NaN,NaN,NaN,2019-02-15
1,1062231,AMERICAN AXLE & MANUFACTURING HOLDINGS INC,0001062231-20-000009,2019-12-31,1.81,NaN,0.52,831400000.0,-1.39,NaN,0.00,0.01,NaN,NaN,NaN,2020-02-14
2,1062231,AMERICAN AXLE & MANUFACTURING HOLDINGS INC,0001062231-21-000013,2020-12-31,1.92,NaN,0.57,897700000.0,-1.87,NaN,0.00,0.00,-0.0,NaN,0.01,2021-02-12
3,1062231,AMERICAN AXLE & MANUFACTURING HOLDINGS INC,0001062231-22-000008,2021-12-31,1.78,NaN,0.51,816100000.0,1.23,NaN,0.56,0.01,NaN,NaN,NaN,2022-02-11
4,1062231,AMERICAN AXLE & MANUFACTURING HOLDINGS INC,0001062231-23-000016,2022-12-31,1.66,NaN,0.43,794100000.0,1.40,NaN,0.54,0.03,NaN,NaN,NaN,2023-02-17
5,1062231,AMERICAN AXLE & MANUFACTURING HOLDINGS INC,0001062231-24-000007,2023-12-31,1.67,NaN,0.43,805000000.0,0.73,NaN,0.52,0.01,NaN,NaN,NaN,2024-02-16
6,1062231,AMERICAN AXLE & MANUFACTURING HOLDINGS INC,0001062231-25-000008,2024-12-31,1.63,NaN,0.47,739600000.0,1.30,NaN,0.53,0.02,NaN,NaN,NaN,2025-02-14

In [13]:
conn.sql("SELECT * FROM gold.fact_financial_metrics").df()

,accession_number,period_end,current_ratio,quick_ratio,cash_ratio,net_working_capital,interest_coverage_ratio,ocf_debt_ratio,debt_to_assets_ratio,short_term_debt_ratio,cash_earnings_conversion,fcf_to_debt_ratio,return_on_assets,filed
0,0000018230-19-000153,2018-12-31,1.37,NaN,0.00,1.038500e+10,NaN,NaN,0.00,NaN,NaN,NaN,NaN,2019-05-06
1,0001144204-19-024655,2019-03-31,1.46,NaN,0.20,1.509830e+08,1.83,NaN,0.00,NaN,-12.42,NaN,0.00,2019-05-09
2,0001564590-19-013462,2018-12-31,0.83,NaN,0.37,-1.685828e+09,NaN,NaN,0.00,0.69,NaN,NaN,NaN,2019-04-29
3,0000775158-19-000055,2018-09-30,1.93,NaN,0.27,1.579800e+09,NaN,NaN,0.15,0.00,NaN,NaN,NaN,2019-04-30
4,0001564590-19-015329,2018-12-31,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,2019-05-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10080,0001493152-20-009565,2019-12-31,0.08,NaN,0.07,-1.222101e+06,NaN,NaN,0.00,NaN,NaN,NaN,NaN,2020-05-20
10081,0001477932-20-003485,2018-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,2020-06-22
10082,0001589526-20-000063,2020-03-31,1.14,NaN,0.20,2.483600e+07,0.76,NaN,0.47,0.06,0.00,NaN,-0.00,2020-05-14
10083,0000014195-20-000029,2020-03-31,0.91,NaN,0.05,-8.663500e+07,-8.58,NaN,0.38,1.00,0.00,NaN,-0.09,2020-05-08
10084,0000763744-20-000062,2019-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.53,NaN,NaN,2020-05-07